// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transfer.proto

package transfer // import "."

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChatRequestAndResponse struct {
	FromConnector        string   `protobuf:"bytes,1,opt,name=from_connector,json=fromConnector" json:"from_connector,omitempty"`
	ToConnector          string   `protobuf:"bytes,2,opt,name=to_connector,json=toConnector" json:"to_connector,omitempty"`
	Data                 *Data    `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatRequestAndResponse) Reset()         { *m = ChatRequestAndResponse{} }
func (m *ChatRequestAndResponse) String() string { return proto.CompactTextString(m) }
func (*ChatRequestAndResponse) ProtoMessage()    {}
func (*ChatRequestAndResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_5390bc961e9d874e, []int{0}
}
func (m *ChatRequestAndResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatRequestAndResponse.Unmarshal(m, b)
}
func (m *ChatRequestAndResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatRequestAndResponse.Marshal(b, m, deterministic)
}
func (dst *ChatRequestAndResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatRequestAndResponse.Merge(dst, src)
}
func (m *ChatRequestAndResponse) XXX_Size() int {
	return xxx_messageInfo_ChatRequestAndResponse.Size(m)
}
func (m *ChatRequestAndResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatRequestAndResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChatRequestAndResponse proto.InternalMessageInfo

func (m *ChatRequestAndResponse) GetFromConnector() string {
	if m != nil {
		return m.FromConnector
	}
	return ""
}

func (m *ChatRequestAndResponse) GetToConnector() string {
	if m != nil {
		return m.ToConnector
	}
	return ""
}

func (m *ChatRequestAndResponse) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type Data struct {
	FromId               string   `protobuf:"bytes,1,opt,name=from_id,json=fromId" json:"from_id,omitempty"`
	ToId                 string   `protobuf:"bytes,2,opt,name=to_id,json=toId" json:"to_id,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_5390bc961e9d874e, []int{1}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetFromId() string {
	if m != nil {
		return m.FromId
	}
	return ""
}

func (m *Data) GetToId() string {
	if m != nil {
		return m.ToId
	}
	return ""
}

func (m *Data) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatRequestAndResponse)(nil), "hello.ChatRequestAndResponse")
	proto.RegisterType((*Data)(nil), "hello.Data")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Transfer service

type TransferClient interface {
	Chat(ctx context.Context, opts ...grpc.CallOption) (Transfer_ChatClient, error)
}

type transferClient struct {
	cc *grpc.ClientConn
}

func NewTransferClient(cc *grpc.ClientConn) TransferClient {
	return &transferClient{cc}
}

func (c *transferClient) Chat(ctx context.Context, opts ...grpc.CallOption) (Transfer_ChatClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Transfer_serviceDesc.Streams[0], c.cc, "/hello.Transfer/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &transferChatClient{stream}
	return x, nil
}

type Transfer_ChatClient interface {
	Send(*ChatRequestAndResponse) error
	Recv() (*ChatRequestAndResponse, error)
	grpc.ClientStream
}

type transferChatClient struct {
	grpc.ClientStream
}

func (x *transferChatClient) Send(m *ChatRequestAndResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transferChatClient) Recv() (*ChatRequestAndResponse, error) {
	m := new(ChatRequestAndResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Transfer service

type TransferServer interface {
	Chat(Transfer_ChatServer) error
}

func RegisterTransferServer(s *grpc.Server, srv TransferServer) {
	s.RegisterService(&_Transfer_serviceDesc, srv)
}

func _Transfer_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransferServer).Chat(&transferChatServer{stream})
}

type Transfer_ChatServer interface {
	Send(*ChatRequestAndResponse) error
	Recv() (*ChatRequestAndResponse, error)
	grpc.ServerStream
}

type transferChatServer struct {
	grpc.ServerStream
}

func (x *transferChatServer) Send(m *ChatRequestAndResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transferChatServer) Recv() (*ChatRequestAndResponse, error) {
	m := new(ChatRequestAndResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Transfer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Transfer",
	HandlerType: (*TransferServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _Transfer_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "transfer.proto",
}

func init() { proto.RegisterFile("transfer.proto", fileDescriptor_transfer_5390bc961e9d874e) }

var fileDescriptor_transfer_5390bc961e9d874e = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x8d, 0x4d, 0xab, 0x9d, 0xad, 0x45, 0x46, 0xd0, 0x22, 0x88, 0x75, 0x41, 0xd8, 0x53,
	0x90, 0x7a, 0xf4, 0xa4, 0x15, 0xa1, 0x1e, 0x83, 0x78, 0xf0, 0x22, 0xb1, 0x49, 0xad, 0xd0, 0xcd,
	0xac, 0xc9, 0xf8, 0x0b, 0xfc, 0xe3, 0x92, 0xb8, 0x8b, 0x1e, 0xc4, 0xdb, 0xcc, 0x9b, 0xc7, 0x7c,
	0xbc, 0x07, 0x63, 0x0e, 0xc6, 0xc7, 0x95, 0x0b, 0xaa, 0x09, 0xc4, 0x84, 0xfd, 0xb5, 0xdb, 0x6c,
	0xa8, 0xfc, 0x14, 0x70, 0x38, 0x5f, 0x1b, 0xd6, 0xee, 0xfd, 0xc3, 0x45, 0xbe, 0xf6, 0x56, 0xbb,
	0xd8, 0x90, 0x8f, 0x0e, 0xcf, 0x61, 0xbc, 0x0a, 0x54, 0x3f, 0x2f, 0xc9, 0x7b, 0xb7, 0x64, 0x0a,
	0x13, 0x31, 0x15, 0xd5, 0x50, 0xef, 0x25, 0x75, 0xde, 0x89, 0x78, 0x06, 0x23, 0xa6, 0x5f, 0xa6,
	0xed, 0x6c, 0x2a, 0x98, 0x7e, 0x2c, 0xa7, 0x20, 0xad, 0x61, 0x33, 0xe9, 0x4d, 0x45, 0x55, 0xcc,
	0x0a, 0x95, 0xd1, 0xea, 0xd6, 0xb0, 0xd1, 0xf9, 0x50, 0xde, 0x81, 0x4c, 0x1b, 0x1e, 0xc1, 0x4e,
	0x46, 0xbe, 0xd9, 0x96, 0x35, 0x48, 0xeb, 0xc2, 0xe2, 0x01, 0xf4, 0x99, 0x92, 0xfc, 0xfd, 0x5d,
	0x32, 0x2d, 0x2c, 0xee, 0x43, 0xaf, 0x8e, 0xaf, 0xf9, 0xeb, 0x50, 0xa7, 0x71, 0xf6, 0x08, 0xbb,
	0x0f, 0x6d, 0x4c, 0xbc, 0x07, 0x99, 0x82, 0xe1, 0x49, 0x8b, 0xfb, 0x3b, 0xe5, 0xf1, 0xff, 0xe7,
	0x72, 0xab, 0x12, 0x17, 0xe2, 0x66, 0xf4, 0x04, 0xea, 0xaa, 0x2b, 0xf0, 0x65, 0x90, 0x1b, 0xbc,
	0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x1c, 0x5a, 0xa0, 0x53, 0x01, 0x00, 0x00,
}
