server:
    address: ":8080"

rpcServer:
    address: "localhost:8972"

mongodb:
    host: "localhost"
    port: 27017
    username: "root"
    password: "123456"
    database: "im"

redis:
    host: "localhost"
    port: 6379
    password: ""
    database: 0

rabbitmq:
    host: "localhost"
    port: 5672
    username: "root"
    password: "123456"

etcd:
    host: "localhost"
    port: 2379
    username: ""
    password: ""

jwt:
    encryptKey: "my jwt encrypt key"
    expireHours: 24